### ISSUE TITLE
CRITICAL can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by brylie** [singer-io/tap-chargebee#31]
When running the tap-chargebee in sync mode, it fails with the following traceback:

```
INFO METRIC: {"type": "counter", "metric": "record_count", "value": 100, "tags": {"endpoint": "events"}}
ERROR can't compare offset-naive and offset-aware datetimes
ERROR Failed to sync endpoint events, moving on!
CRITICAL can't compare offset-naive and offset-aware datetimes
Traceback (most recent call last):
  File "./tap-chargebee/bin/tap-chargebee", line 8, in <module>
    sys.exit(main())
  File "/home/brylie/Code/MaaS_Global/singer/tap-chargebee/lib/python3.8/site-packages/singer/utils.py", line 192, in wrapped
    return fnc(*args, **kwargs)
  File "/home/brylie/Code/MaaS_Global/singer/tap-chargebee/lib/python3.8/site-packages/tap_chargebee/__init__.py", line 27, in main
    runner.do_sync()
  File "/home/brylie/Code/MaaS_Global/singer/tap-chargebee/lib/python3.8/site-packages/tap_framework/__init__.py", line 81, in do_sync
    raise e
  File "/home/brylie/Code/MaaS_Global/singer/tap-chargebee/lib/python3.8/site-packages/tap_framework/__init__.py", line 71, in do_sync
    stream.sync()
  File "/home/brylie/Code/MaaS_Global/singer/tap-chargebee/lib/python3.8/site-packages/tap_framework/streams.py", line 142, in sync
    return self.sync_data()
  File "/home/brylie/Code/MaaS_Global/singer/tap-chargebee/lib/python3.8/site-packages/tap_chargebee/streams/base.py", line 193, in sync_data
    max_date = max(
TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by fosk06** [comment]
Hello,
I have the same issue

**Comment by fosk06** [comment]
INFO METRIC: {"type": "counter", "metric": "record_count", "value": 54, "tags": {"endpoint": "customers"}}
ERROR can't compare offset-naive and offset-aware datetimes
ERROR Failed to sync endpoint customers, moving on!
CRITICAL can't compare offset-naive and offset-aware datetimes
Traceback (most recent call last):
  File "./tapvenv/bin/tap-chargebee", line 11, in <module>
    load_entry_point('tap-chargebee==1.0.3', 'console_scripts', 'tap-chargebee')()
  File "/Users/tTrividic/code/python/data-workflows/tapvenv/lib/python3.7/site-packages/singer/utils.py", line 192, in wrapped
    return fnc(*args, **kwargs)
  File "/Users/tTrividic/code/python/data-workflows/tapvenv/lib/python3.7/site-packages/tap_chargebee/__init__.py", line 27, in main
    runner.do_sync()
  File "/Users/tTrividic/code/python/data-workflows/tapvenv/lib/python3.7/site-packages/tap_framework/__init__.py", line 81, in do_sync
    raise e
  File "/Users/tTrividic/code/python/data-workflows/tapvenv/lib/python3.7/site-packages/tap_framework/__init__.py", line 71, in do_sync
    stream.sync()
  File "/Users/tTrividic/code/python/data-workflows/tapvenv/lib/python3.7/site-packages/tap_framework/streams.py", line 142, in sync
    return self.sync_data()
  File "/Users/tTrividic/code/python/data-workflows/tapvenv/lib/python3.7/site-packages/tap_chargebee/streams/base.py", line 195, in sync_data
    parse(item.get(bookmark_key))
TypeError: can't compare offset-naive and offset-aware datetimes
